services:
  backend:
    build: ./server
    container_name: mern-backend
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: mern-frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - backend
