services:
  backend:
    build: ./server
    container_name: mern-backend
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
      args:
        - VITE_API_URL=http://3.88.220.184:5001/api
    container_name: mern-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
